site_name: Slowist's Note
site_url: https://slowist-lee.github.io/notebook/
theme:
  name: material
  icon:
    logo: material/book
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font: false
    # code: JetBrains Mono
  # icon:
    # logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
repo_url: https://github.com/Slowist-Lee/notebook
repo_name: Slowist/Notebook
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Slowist-Lee/slowist-notebook
    - icon: fontawesome/regular/envelope 
      link: mailto:<leexin005@163.com> 

  feedback:
    title: 此页面有帮助吗？
    ratings:
      - icon: material/thumb-up-outline
        name: This page was helpful
        data: 1
        note: >-
          谢谢你的反馈！
      - icon: material/thumb-down-outline
        name: This page could be improved
        data: 0
        note: >-
          Thanks for your feedback! Help us improve this page by
          using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.

plugins:
  - search
  - statistics
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: Copyright &copy; Slowist/All Rights Reserved. # 左下角的版权声明

nav:
  - index.md
  - algorithm:
    - algorithm/index.md
    - cs61b:
      - algorithm/cs61b/index.md
      - Lecture1 Introduction: algorithm/cs61b/Lecture1_Introduction.md
      - Lecture2 Defining and Using Classes: algorithm/cs61b/Lecture2_Defining and Using Classes.md
      - Lecture3 ListsI References Recursion and Lists: algorithm/cs61b/Lecture3_ListsI_References_Recursion_and_Lists.md
  - Computer Vision:
      - Computer Vision/index.md
      - Introduction to CV:
        - Computer Vision/Introduction to CV/index.md
        - Lecture 1: Computer Vision/Introduction to CV/Lecture 1.md
  - Math: 
    - Math/index.md
    - 复变函数与积分变换: Math/Complex/index.md
  - EE: 
    - EE/index.md
    - 电子电路基础: 
      - EE/EletronicsFundamental/index.md
      - 模电: 
        - EE/EletronicsFundamental/Analog/index.md
        - MOS:
          - EE/EletronicsFundamental/Analog/MOS/index.md
        - 多级、差分:
          - EE/EletronicsFundamental/Analog/Hard/index.md
        - 运算放大器:
          - EE/EletronicsFundamental/Analog/opam/index.md
        - 频率响应:
          - EE/EletronicsFundamental/Analog/freq/index.md
  - English:
    - Interpretation: 
      - Language/Interpretation/index.md
      - 学习体验:
        - Language/Interpretation/Harvest.md
        - Language/Interpretation/Interpretation--Self Assessment.md
      - HW && Topic: 
        - Language/Interpretation/Welcome Speech.md
        - Language/Interpretation/City and Travel.md
        - Language/Interpretation/Culture and Education.md
        - Language/Interpretation/Science.md
      - Learning Resources:
        - Language/Interpretation/Material.md
  - Others: 
    - Others/index.md
    - Others/雕版印刷与刻本文化.md
  - Writings:
    - Writings/index.md
    - 01: Writings/01.md
    - 02: Writings/02.md
    - 03: Writings/03.md
    - 04: Writings/04.md
    - 05: Writings/05.md
    - 06: Writings/06.md
    - 07: Writings/07.md
    - 08: Writings/08.md
    - 09: Writings/09.md
    - 10: Writings/10.md
    - 11: Writings/11.md
    - 12: Writings/12.md
    - 13: Writings/13.md
    - 14: Writings/14.md
    - 15: Writings/15.md
    

    